<a href="https://colab.research.google.com/github/NiddanaMohan00/numpy-basic/blob/main/numpybasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.zeros(10,dtype=int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
import numpy as np
a=np.ones(10,dtype=int)
print(a)

[1 1 1 1 1 1 1 1 1 1]


In [ ]:
import numpy as np
a=np.eye(6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [ ]:
import numpy as np
a=np.full((3,3),10)#full((rows,columns),value)
print(a)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
import numpy as np
a=np.arange(10,20,2)#arange(start,stop,step)
print(a)

[10 12 14 16 18]


In [ ]:
import numpy as np
a=np.linspace(10,1000,5,dtype=int)#arange(start,stop,step)
print(a)

[  10  257  505  752 1000]


In [ ]:
import numpy as np
a=45
b=np.array(a)
print(b)
print(b.dtype)
print(b.ndim)


45
int64
0


In [ ]:
import numpy as np
a=(1,2,3,4,4,5)
b=np.array(a)
print(b)
print(b.dtype)
print(b.ndim)
print(b.shape)

[1 2 3 4 4 5]
int64
1
(6,)


In [ ]:
import numpy as np
a=[[1,2,3,4,4,5],[2,4,2,2,4,5]]
b=np.array(a)
print(b)
print(b.dtype)#type of the array
print(b.ndim)#dimentions
print(b.shape)#(rows,columns)
print(b.size)#number values or row*columns
print(b.T)#row into columns
print(b.itemsize)#if it dtype=64 then it is 8 ,if it is 32 then it is 4
print(b.nbytes)#nbytes=size*itemsize


[[1 2 3 4 4 5]
 [2 4 2 2 4 5]]
int64
2
(2, 6)
12
[[1 2]
 [2 4]
 [3 2]
 [4 2]
 [4 4]
 [5 5]]
8
96


In [ ]:
import numpy as np
a=[[1,2,3,4,4,5],[2,4,2,2,4,5]]
b=np.array(a,dtype=np.int32)
print(b)
print(b.dtype)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.T)
print(b.itemsize)
c=b.reshape(3,4)
print(c)

[[1 2 3 4 4 5]
 [2 4 2 2 4 5]]
int32
2
(2, 6)
12
[[1 2]
 [2 4]
 [3 2]
 [4 2]
 [4 4]
 [5 5]]
4
[[1 2 3 4]
 [4 5 2 4]
 [2 2 4 5]]


In [ ]:
#methods................
import numpy as np
a=[1,2,3,4,5,5,8]
b=np.array(a)
print(b[-1])
print(b[0:2])
print(b.sum())

8
[1 2]
28


In [ ]:
import numpy as np
a=[[1,2,3,4,4,5],[2,4,2,2,4,5]]
b=np.array(a)
print(a[-1])
print(a[1][-2])


[2, 4, 2, 2, 4, 5]
4


In [ ]:
import numpy as np
a=[[1,2,3,4,4,5],[2,4,2,2,4,5]]
b=np.array(a)
print(b.sum())

38


In [ ]:
import numpy as np
a=[[1,2,3,4,4,5,10],[2,4,2,2,4,5,9]]
b=np.array(a)
print(b.max())
print(b.sum())

10
57


In [ ]:
import numpy as np
a=[[1,2,3,4,4,5,10],[2,4,2,2,4,5,9]]
b=np.array(a)
print(b.min())

1


In [ ]:
import numpy as np
a=[[1,2,3,4,4,5,10],[2,4,2,2,4,5,9]]
b=np.array(a)
print(b.mean())

4.071428571428571


In [ ]:
import numpy as np
a=[[1,2,3,4,4,5,10],[2,4,2,2,4,5,9]]
b=np.array(a)
print(b.std())
print(b.var())

2.520325537768193
6.3520408163265305


In [ ]:
import numpy as np
a=[[1,2,3,4,4,5,10],[2,4,2,2,4,5,9]]
b=np.array(a)
print(np.sqrt(b.std()))

1.587553318086732


In [ ]:
import numpy as np
a=[[1,2,3,4,4,5,10],[2,4,2,2,4,5,9]]
b=np.array(a)
print(np.sort(b))#sort individual rows in accending order

[[ 1  2  3  4  4  5 10]
 [ 2  2  2  4  4  5  9]]


In [ ]:
import numpy as np
a=[[1,2,3],[2,4,2],[2,4,2]]
b=np.array(a)
print(b)
print(np.diagonal(b))#print diagonal values

[[1 2 3]
 [2 4 2]
 [2 4 2]]
[1 4 2]


In [ ]:
import numpy as np
a=[[1,2,3],[2,4,2],[2,4,2]]
b=np.array(a)
print(b)
print(b.trace())#diagonals sum

[[1 2 3]
 [2 4 2]
 [2 4 2]]
7


In [ ]:
import numpy as np
a=[[1,2,3],[-2,0,2],[2,4,2]]
b=np.array(a)
print(b)
print(np.count_nonzero(b))#number of non zero values

[[ 1  2  3]
 [-2  0  2]
 [ 2  4  2]]
8


In [ ]:
import numpy as np
a=[[1,2,3],[0,0,2],[2,4,2]]
b=np.array(a)
d=b.size
c=np.count_nonzero(b)
print(d-c)

2


In [ ]:
import numpy as np
a=[[1,2,3],[0,0,2],[2,4,2]]
b=np.array(a)
print(b+5)

[[6 7 8]
 [5 5 7]
 [7 9 7]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[0,0,2],[2,4,2]])
print(a)
b=np.array([[1,2,3],[0,0,2],[2,4,2]])
print(b)
print(np.add(a,b))


[[1 2 3]
 [0 0 2]
 [2 4 2]]
[[1 2 3]
 [0 0 2]
 [2 4 2]]
[[2 4 6]
 [0 0 4]
 [4 8 4]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[0,0,2],[2,4,2]])
print(a)
b=np.array([[1,2,3],[0,0,-1],[2,4,2]])
print(b)
print(np.subtract(a,b))

[[1 2 3]
 [0 0 2]
 [2 4 2]]
[[ 1  2  3]
 [ 0  0 -1]
 [ 2  4  2]]
[[0 0 0]
 [0 0 3]
 [0 0 0]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[0,0,2],[2,4,2]])
print(a)
b=np.array([[1,2,3],[0,0,-1],[2,4,2]])
print(b)
print(np.multiply(a,b))

[[1 2 3]
 [0 0 2]
 [2 4 2]]
[[ 1  2  3]
 [ 0  0 -1]
 [ 2  4  2]]
[[ 1  4  9]
 [ 0  0 -2]
 [ 4 16  4]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[0,0,2],[2,4,2]])
print(a)
b=np.array([[1,2,3],[1,1,1],[2,4,2]])
print(b)
print(np.divide(a,b))

[[1 2 3]
 [0 0 2]
 [2 4 2]]
[[1 2 3]
 [1 1 1]
 [2 4 2]]
[[1. 1. 1.]
 [0. 0. 2.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
a=np.array([[1,8,3],[0,7,2],[2,4,2]])
print(a)
b=np.array([[1,11,3],[1,1,1],[2,4,2]])
print(b)
print(np.mod(a,b))

[[1 8 3]
 [0 7 2]
 [2 4 2]]
[[ 1 11  3]
 [ 1  1  1]
 [ 2  4  2]]
[[0 8 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np
b=np.array([[1,2,3],[0,0,2],[2,4,2]])
print(b)
print(b.flatten())#conver multi dimention to single dimention

[[1 2 3]
 [0 0 2]
 [2 4 2]]
[1 2 3 0 0 2 2 4 2]


In [ ]:
a=[10,20,34,35,35]
b=[23,3,23,23,233]
print(np.dot(a,b))


10032


In [ ]:
import numpy as np
a=np.array([[1,2,3],[0,0,2],[2,4,2]])
print(a)
b=np.array([[1,2,3],[0,0,-1],[2,4,2]])
print(b)
print(np.dot(a,b))

[[1 2 3]
 [0 0 2]
 [2 4 2]]
[[ 1  2  3]
 [ 0  0 -1]
 [ 2  4  2]]
[[ 7 14  7]
 [ 4  8  4]
 [ 6 12  6]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[0,0,2],[2,4,2]])
print(a)
b=np.array([[1,2,3],[0,0,-1],[2,4,2]])
print(b)
print(np.hstack((a,b)))

[[1 2 3]
 [0 0 2]
 [2 4 2]]
[[ 1  2  3]
 [ 0  0 -1]
 [ 2  4  2]]
[[ 1  2  3  1  2  3]
 [ 0  0  2  0  0 -1]
 [ 2  4  2  2  4  2]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[0,0,2],[2,4,2]])
print(a)
b=np.array([[1,2,3],[0,0,-1],[2,4,2]])
print(b)
print(np.vstack((a,b)))

[[1 2 3]
 [0 0 2]
 [2 4 2]]
[[ 1  2  3]
 [ 0  0 -1]
 [ 2  4  2]]
[[ 1  2  3]
 [ 0  0  2]
 [ 2  4  2]
 [ 1  2  3]
 [ 0  0 -1]
 [ 2  4  2]]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A)
print(B)
print(A + B)
print(np.dot(A, B))
print(np.transpose(A))
print(np.linalg.inv(A))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
